USE [master]
GO
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'tempdev', SIZE = 5GB , FILEGROWTH = 256MB,  MAXSIZE = 5376MB )
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'templog', SIZE = 2097152KB , FILEGROWTH = 256MB )
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'temp2', SIZE = 5GB , FILEGROWTH = 256MB,  MAXSIZE = 5376MB  )
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'temp3', SIZE = 5GB , FILEGROWTH = 256MB,  MAXSIZE = 5376MB )
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'temp4', SIZE = 5GB , FILEGROWTH = 256MB,  MAXSIZE = 5376MB )
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'temp5', SIZE = 5GB , FILEGROWTH = 256MB,  MAXSIZE = 5376MB )
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'temp6', SIZE = 5GB , FILEGROWTH = 256MB,  MAXSIZE = 5376MB )
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'temp7', SIZE = 5GB , FILEGROWTH = 256MB,  MAXSIZE = 5376MB )
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'temp8', SIZE = 5GB , FILEGROWTH = 256MB,  MAXSIZE = 5376MB )
GO